### PR TITLE
Added code, examples

### PR DESCRIPTION
**Pull request by marcneuwirth**
- Added examples
- Simplfied options for shallow copy
- Added fade
- Fixed arrow

### CODE REVIEW

**Comment by zmaril** [comment]
Awesome! This mirrors some work that I've been doing that I haven't pushed yet. I'll push it soon and then start pulling all of this in bit by bit.

**Comment by zmaril** [comment]
I had made a mistake when updating previously and forget to include a ton of files. I was reorganizing folders and things got misplaced. Thus, the coffeescript source is now included for the project. If you want to rewrite the code using this new structure/language, I would be happy to merge it. If not, just say the word, and I will take in your work as it applies and use it. My apologies on the run around. 

We both had hit on a shallow structure for the returned object as well as adding in more examples. I will definitely get your fade code in there soon and probably add in a option to control the length of the fade. Also, it looks like you figured out an simpler way to do the css arrows.

Thank you for the code! I am closing this because it cannot be merged in it's current form.

**Comment by marcneuwirth** [comment]
No problem, I will merge some of this in to the new coffeescript

**Comment by zmaril** [comment]
Great! Thanks. Looking forward to it.

**Pull request closed without merging**
